/**
 * Common vehicle makes and their models, plus common mod names per category.
 * Used for autocomplete suggestions in add-car and add-mod forms.
 *
 * This is NOT exhaustive — it's a sensible quick-pick list. Users can always
 * type custom values; autocomplete is just a convenience layer.
 */

export const VEHICLE_MAKES: string[] = [
  "Acura", "Alfa Romeo", "Aston Martin", "Audi", "Bentley",
  "BMW", "Bugatti", "Buick", "Cadillac", "Chevrolet",
  "Chrysler", "Dodge", "Ferrari", "Fiat", "Ford",
  "Genesis", "GMC", "Honda", "Hyundai", "Infiniti",
  "Jaguar", "Jeep", "Kia", "Koenigsegg", "Lamborghini",
  "Land Rover", "Lexus", "Lincoln", "Lotus", "Maserati",
  "Mazda", "McLaren", "Mercedes-Benz", "Mini", "Mitsubishi",
  "Nissan", "Pagani", "Polestar", "Pontiac", "Porsche",
  "Ram", "Rivian", "Rolls-Royce", "Saab", "Scion",
  "Subaru", "Suzuki", "Tesla", "Toyota", "Volkswagen",
  "Volvo",
];

export const VEHICLE_MODELS: Record<string, string[]> = {
  Acura: ["Integra", "NSX", "RSX", "TL", "TSX", "RDX", "MDX", "TLX"],
  "Alfa Romeo": ["4C", "Giulia", "Stelvio", "Giulietta"],
  "Aston Martin": ["DB11", "DBS", "Vantage", "DBX"],
  Audi: [
    "A3", "A4", "A5", "A6", "A7", "A8", "Q3", "Q5", "Q7", "Q8",
    "RS3", "RS4", "RS5", "RS6", "RS7", "S3", "S4", "S5", "S6", "S7",
    "R8", "TT", "TTS", "TT RS", "e-tron",
  ],
  BMW: [
    "1 Series", "2 Series", "3 Series", "4 Series", "5 Series", "6 Series",
    "7 Series", "8 Series", "X1", "X2", "X3", "X4", "X5", "X6", "X7",
    "Z4", "M2", "M3", "M4", "M5", "M8", "i3", "i4", "i8", "iX", "M240i",
    "335i", "M3 F80", "M3 G80", "M4 F82", "M4 G82",
  ],
  Cadillac: ["ATS", "CT4", "CT5", "CTS", "Escalade", "XT5", "Blackwing"],
  Chevrolet: [
    "Camaro", "Corvette", "Corvette C5", "Corvette C6", "Corvette C7", "Corvette C8",
    "Silverado", "Tahoe", "Suburban", "Colorado", "Cruze", "Malibu", "Impala",
    "Trailblazer", "Blazer", "SS",
  ],
  Dodge: [
    "Challenger", "Charger", "Dart", "Durango", "Viper", "Demon", "Hellcat",
    "Scat Pack", "Challenger SRT", "Charger SRT",
  ],
  Ferrari: ["488", "812", "F8 Tributo", "Portofino", "Roma", "SF90", "LaFerrari", "458"],
  Ford: [
    "Mustang", "Mustang GT", "Mustang GT350", "Mustang GT500", "Mustang Mach 1",
    "Focus", "Focus ST", "Focus RS", "Fiesta", "Fiesta ST", "F-150", "F-150 Raptor",
    "Bronco", "Bronco Raptor", "Explorer", "Edge", "Ranger", "Maverick", "Escape",
    "GT", "Fusion",
  ],
  Genesis: ["G70", "G80", "G90", "GV70", "GV80"],
  GMC: ["Sierra", "Yukon", "Canyon", "Acadia", "Terrain"],
  Honda: [
    "Civic", "Civic Si", "Civic Type R", "Civic SiR", "Accord", "Accord Sport",
    "CR-V", "HR-V", "Pilot", "Passport", "Ridgeline", "Odyssey", "Prelude",
    "S2000", "NSX", "Fit", "Insight", "Del Sol", "CRX", "Integra",
  ],
  Hyundai: ["Elantra", "Elantra N", "Sonata", "Sonata N Line", "Veloster", "Veloster N", "Kona", "Kona N", "Tucson", "Santa Fe", "Palisade", "Genesis Coupe"],
  Infiniti: ["G35", "G37", "Q50", "Q60", "Q70", "QX50", "QX60", "QX80", "M37"],
  Jaguar: ["F-Type", "XE", "XF", "XJ", "F-Pace", "I-Pace"],
  Jeep: ["Wrangler", "Wrangler Rubicon", "Gladiator", "Grand Cherokee", "Grand Cherokee SRT", "Grand Cherokee Trackhawk", "Cherokee", "Compass", "Renegade"],
  Kia: ["Forte", "K5", "Optima", "Stinger", "Soul", "Sorento", "Sportage", "Telluride", "EV6"],
  Lamborghini: ["Huracán", "Aventador", "Urus", "Gallardo", "Murciélago"],
  Lexus: ["IS", "IS-F", "RC", "RC F", "GS", "GS F", "ES", "LS", "LC", "LC 500", "LFA", "NX", "RX", "LX", "GX", "UX"],
  Maserati: ["Ghibli", "Levante", "GranTurismo", "Quattroporte", "MC20"],
  Mazda: ["Mazda3", "Mazdaspeed3", "Mazda6", "Mazdaspeed6", "MX-5 Miata", "MX-5", "RX-7", "RX-8", "CX-3", "CX-30", "CX-5", "CX-9", "CX-50"],
  McLaren: ["570S", "600LT", "720S", "750S", "Artura", "Senna", "P1"],
  "Mercedes-Benz": [
    "A-Class", "C-Class", "E-Class", "S-Class", "CLA", "CLS", "G-Class", "G-Wagon",
    "GLA", "GLC", "GLE", "GLS", "SL", "SLC", "SLK", "AMG GT", "C63 AMG", "E63 AMG",
    "GLC 63 AMG", "GLE 63 AMG", "G63 AMG",
  ],
  Mini: ["Cooper", "Cooper S", "Cooper JCW", "Countryman", "Clubman"],
  Mitsubishi: ["Lancer Evolution", "Evo", "3000GT", "Eclipse", "Outlander", "Mirage"],
  Nissan: [
    "370Z", "350Z", "400Z", "Z", "GT-R", "GT-R Nismo", "Skyline", "Skyline R32", "Skyline R33", "Skyline R34",
    "Silvia", "Silvia S13", "Silvia S14", "Silvia S15", "240SX", "Sentra", "Sentra SE-R",
    "Altima", "Maxima", "Pathfinder", "Rogue", "Frontier", "Titan", "Juke",
  ],
  Porsche: [
    "911", "911 Carrera", "911 Carrera S", "911 Turbo", "911 Turbo S", "911 GT3",
    "911 GT3 RS", "911 GT2 RS", "911 Dakar", "718 Cayman", "718 Cayman GT4",
    "718 Boxster", "718 Spyder", "Cayman", "Boxster", "Macan", "Macan GTS", "Macan Turbo",
    "Cayenne", "Cayenne Turbo", "Panamera", "Panamera Turbo", "Taycan", "Taycan Turbo S",
  ],
  Ram: ["1500", "2500", "3500", "TRX", "Rebel"],
  Rivian: ["R1T", "R1S"],
  Scion: ["FR-S", "tC", "xB", "iQ"],
  Subaru: [
    "Impreza", "Impreza WRX", "WRX", "WRX STI", "STI", "Legacy", "Outback",
    "Forester", "Forester XT", "Crosstrek", "Ascent", "BRZ", "BRZ tS",
  ],
  Tesla: ["Model S", "Model 3", "Model X", "Model Y", "Cybertruck", "Roadster", "Plaid"],
  Toyota: [
    "86", "GR86", "Supra", "MK4 Supra", "MK5 Supra", "Celica", "Celica GT-S",
    "GR Corolla", "Corolla", "Camry", "Camry TRD", "Prius", "Avalon",
    "Tacoma", "Tundra", "4Runner", "Land Cruiser", "Sequoia", "Highlander", "RAV4",
    "Mirai", "MR2", "MR2 Spyder", "Matrix",
  ],
  Volkswagen: [
    "Golf", "Golf GTI", "Golf R", "Jetta", "Jetta GLI", "Passat", "Arteon",
    "Atlas", "Tiguan", "Touareg", "Beetle", "CC", "Rabbit", "ID.4",
  ],
  Volvo: ["S60", "S90", "V60", "V90", "XC40", "XC60", "XC90", "Polestar 1", "Polestar 2"],
};

/**
 * Common mod names per category — used for autocomplete in the add-mod form.
 * Sorted by popularity / how often they appear on enthusiast builds.
 */
export const COMMON_MODS: Record<string, string[]> = {
  engine: [
    "Cold air intake",
    "Tune / ECU flash",
    "Intake manifold",
    "Throttle body",
    "Fuel injectors",
    "High-flow fuel pump",
    "Turbo kit",
    "Bigger turbo",
    "Supercharger kit",
    "Intercooler",
    "Intercooler piping",
    "Charge pipe",
    "Blow-off valve",
    "Wastegate",
    "Downpipe",
    "Catless downpipe",
    "Exhaust headers",
    "Long tube headers",
    "Mid-pipe / X-pipe",
    "Oil catch can",
    "Nitrous kit",
    "Forged pistons",
    "Forged rods",
    "Built short block",
    "Head studs",
    "Head gasket",
    "Cams",
    "Valve springs",
    "Port and polish",
    "Flex fuel sensor",
    "Methanol injection",
    "Radiator upgrade",
    "Oil cooler",
    "Lightweight pulley",
  ],
  suspension: [
    "Coilovers",
    "Lowering springs",
    "Air suspension",
    "Adjustable control arms",
    "Adjustable camber arms",
    "Rear toe arms",
    "Front sway bar",
    "Rear sway bar",
    "Sway bar end links",
    "Strut tower brace",
    "Front strut brace",
    "Rear strut brace",
    "Front lower brace",
    "Subframe brace",
    "Polyurethane bushings",
    "Engine mounts",
    "Transmission mounts",
    "Differential mounts",
    "Alignment",
    "Corner balance",
    "Stiffer springs",
    "KW coilovers",
    "Ohlins coilovers",
    "Bilstein shocks",
    "Fortune Auto coilovers",
    "Tein coilovers",
    "Eibach springs",
    "H&R springs",
  ],
  aero: [
    "Front splitter",
    "Front lip",
    "Rear wing",
    "Rear spoiler",
    "Rear diffuser",
    "Side skirts",
    "Canards",
    "Hood vents",
    "Functional hood vents",
    "Vented hood",
    "Fender vents",
    "Wide body kit",
    "Overfenders",
    "Carbon fiber lip",
    "Carbon fiber splitter",
    "Carbon fiber wing",
    "Carbon fiber diffuser",
    "Carbon fiber hood",
    "Carbon fiber trunk",
    "Windshield banner",
    "Racing livery",
  ],
  interior: [
    "Racing seats",
    "Bucket seats",
    "Sparco seats",
    "Recaro seats",
    "Bride seats",
    "Harness bar",
    "4-point harness",
    "5-point harness",
    "Roll bar",
    "Roll cage",
    "Steering wheel",
    "Momo steering wheel",
    "Sparco steering wheel",
    "Quick release hub",
    "Shift knob",
    "Short shifter",
    "Short throw shifter",
    "Dead pedal",
    "Pedal covers",
    "Carbon fiber trim",
    "Alcantara trim",
    "Custom stitching",
    "Gauge cluster",
    "Boost gauge",
    "AFR gauge",
    "Oil pressure gauge",
    "Water temp gauge",
    "Floor mats",
    "Subwoofer",
    "Amplifier",
    "Head unit",
    "Sound deadening",
  ],
  wheels: [
    "New wheels",
    "Wheel spacers",
    "Extended lug studs",
    "Tires",
    "Summer tires",
    "Track tires",
    "Winter tires",
    "Brake kit",
    "Big brake kit",
    "Brembo brakes",
    "AP Racing brakes",
    "Stoptech brakes",
    "Brake pads",
    "Brake lines",
    "Stainless brake lines",
    "Brake fluid",
    "Drilled rotors",
    "Slotted rotors",
    "Two-piece rotors",
    "Lug nuts",
    "Hub-centric rings",
    "Volk wheels",
    "Work wheels",
    "BBS wheels",
    "Enkei wheels",
    "Vossen wheels",
    "Rays wheels",
  ],
  exhaust: [
    "Cat-back exhaust",
    "Axle-back exhaust",
    "Full exhaust system",
    "Muffler delete",
    "Resonator delete",
    "High-flow cat",
    "Test pipes",
    "Titanium exhaust",
    "Stainless exhaust",
    "Akrapovic exhaust",
    "Borla exhaust",
    "Magnaflow exhaust",
    "Invidia exhaust",
    "Milltek exhaust",
    "Remus exhaust",
    "Fi Exhaust",
    "Armytrix exhaust",
    "Valved exhaust",
    "Electronic cutout",
  ],
  electronics: [
    "Tune / flash",
    "Standalone ECU",
    "Piggyback tune",
    "Engine management",
    "AEM Infinity",
    "Haltech ECU",
    "Link ECU",
    "AFR gauge",
    "Wideband O2 sensor",
    "Data logger",
    "Dashcam",
    "LED headlights",
    "HID headlights",
    "LED fog lights",
    "LED taillights",
    "Interior LED lights",
    "Daytime running lights",
    "Underglow lights",
    "Head-up display",
    "Launch control",
    "Anti-lag",
    "Flat foot shifting",
  ],
  other: [
    "Paint protection film",
    "Ceramic coating",
    "Vinyl wrap",
    "Full wrap",
    "Partial wrap",
    "Tinted windows",
    "Window tint",
    "Headlight tint",
    "Taillight tint",
    "Debadge",
    "Custom badges",
    "License plate frame",
    "Detailing",
    "Paint correction",
    "Undercarriage coating",
    "Sound deadening",
    "Battery upgrade",
    "Lightweight battery",
    "Weight reduction",
  ],
};

export function searchMakes(query: string, limit = 8): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return VEHICLE_MAKES.slice(0, limit);
  return VEHICLE_MAKES.filter((m) => m.toLowerCase().includes(q)).slice(0, limit);
}

export function searchModels(make: string, query: string, limit = 10): string[] {
  const models = VEHICLE_MODELS[make] ?? [];
  const q = query.trim().toLowerCase();
  if (!q) return models.slice(0, limit);
  return models.filter((m) => m.toLowerCase().includes(q)).slice(0, limit);
}

export function searchMods(category: string, query: string, limit = 8): string[] {
  const mods = COMMON_MODS[category] ?? COMMON_MODS.other;
  const q = query.trim().toLowerCase();
  if (!q) return mods.slice(0, limit);
  return mods.filter((m) => m.toLowerCase().includes(q)).slice(0, limit);
}
